name: Print Date on Branch Creation

on:
  create:
    branches:
      - '*'

jobs:
  print-date:
    runs-on: ubuntu-latest
    steps:
      - name: Print the current date and time
        run: date
