name: Backup GitHub Org to GitLab

on:
  workflow_dispatch:
    inputs:
      github_org:
        description: 'GitHub Organization Name'
        required: true
        type: string
      gitlab_namespace:
        description: 'GitLab Namespace (group or username)'
        required: true
        type: string

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip
          pip install github-backup

      - name: Backup GitHub metadata and clone repos
        run: |
          mkdir backup
          cd backup
          github-backup ${{ inputs.github_org }} -t $GH_PAT -o ./metadata --repositories --issues --pull-requests --wiki --all

      - name: Push to GitLab
        run: |
          for repo_dir in backup/*.git; do
            repo_name=$(basename "$repo_dir" .git)

            echo "Creating repo $repo_name in GitLab..."
            curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
              --data "name=$repo_name&namespace_id=${{ inputs.gitlab_namespace }}" \
              https://gitlab.com/api/v4/projects

            echo "Pushing to GitLab..."
            cd "$repo_dir"
            git push --mirror https://oauth2:$GITLAB_TOKEN@gitlab.com/${{ inputs.gitlab_namespace }}/$repo_name.git
            cd ..
          done
