name: Backup and migrate GitHub org repos to GitLab

on:
  workflow_dispatch:
    inputs:
      github_org:
        description: 'GitHub organization name'
        required: true
      gitlab_group:
        description: 'GitLab group/namespace for import'
        required: true
      project:
        description: 'GitLab project name (optional)'
        required: false
      gitlab_host:
        description: 'GitLab host domain (e.g. gitlab.com)'
        required: true
        default: 'gitlab.com'
      repos:
        description: 'Comma-separated GitHub repo names (optional - empty means all repos)'
        required: false
        default: ''

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GL_TOKEN: ${{ secrets.GL_TOKEN }}

jobs:
  backup-and-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (to get scripts)
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq git curl python3 python3-pip
          pip install requests

      - name: Set script permissions
        run: |
          chmod +x scripts/export_github.sh scripts/import_gitlab.sh

      - name: Export GitHub repos (code)
        run: |
          ./scripts/export_github.sh "${{ github.event.inputs.github_org }}" "${{ github.event.inputs.repos }}"

      - name: Import repos to GitLab (code)
        run: |
          ./scripts/import_gitlab.sh "${{ github.event.inputs.gitlab_group }}" "${{ github.event.inputs.gitlab_host }}"

      - name: Export GitHub metadata (issues, PRs, etc.)
        run: |
          python3 scripts/export_metadata.py "${{ github.event.inputs.github_org }}" "${{ github.event.inputs.repos }}"

      - name: Import metadata to GitLab
        run: |
          python3 scripts/import_metadata.py "${{ github.event.inputs.gitlab_group }}" "${{ github.event.inputs.gitlab_host }}" "${{ github.event.inputs.github_org }}"

